# Generated by Django 5.2.15 on 2026-06-15 23:55

import django.db.models.deletion
import plannings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0002_planning_permissions'),
        ('surgeries', '0002_alter_intervention_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningAuditEvent',
            fields=[
                ('id', models.CharField(default=plannings.models.new_uuid, max_length=36, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('planning_requested', 'Planning requested'), ('planning_request_failed', 'Planning request failed'), ('planning_created', 'Planning created'), ('scheduler_callback_completed', 'Scheduler callback completed'), ('scheduler_callback_failed', 'Scheduler callback failed'), ('planning_approved', 'Planning approved'), ('planning_deleted', 'Planning deleted'), ('surgery_scheduled_from_planning', 'Surgery scheduled from planning')], db_index=True, max_length=80)),
                ('actor_email', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('scheduler', 'Scheduler'), ('system', 'System')], db_index=True, max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_audit_events', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='plannings.planning')),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_audit_events', to='surgeries.surgery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
