# Generated by Django 5.2.15 on 2026-06-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0003_planningauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planningauditevent',
            name='action',
            field=models.CharField(choices=[('planning_requested', 'Planning requested'), ('planning_request_failed', 'Planning request failed'), ('planning_created', 'Planning created'), ('scheduler_callback_completed', 'Scheduler callback completed'), ('scheduler_callback_failed', 'Scheduler callback failed'), ('planning_pending_approval', 'Planning pending approval'), ('planning_approved', 'Planning approved'), ('planning_rejected', 'Planning rejected'), ('planning_deleted', 'Planning deleted'), ('surgery_scheduled_from_planning', 'Surgery scheduled from planning')], db_index=True, max_length=80),
        ),
    ]
