from django.db import migrations, models
import django.db.models.deletion
import surgeries.models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="AnesthesiaType", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=120, unique=True)), ("descripcion", models.TextField(blank=True, null=True)), ("estado", models.BooleanField(default=True))]),
        migrations.CreateModel(name="Intervention", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=180)), ("descripcion", models.TextField(blank=True, null=True)), ("estado", models.BooleanField(default=True))]),
        migrations.CreateModel(name="MedicalStaff", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=255)), ("rol", models.CharField(max_length=40)), ("estado", models.BooleanField(default=True))], options={"ordering": ["nombre"]}),
        migrations.CreateModel(name="OperatingRoom", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=120, unique=True)), ("piso", models.CharField(blank=True, max_length=30, null=True)), ("disponible", models.BooleanField(default=True)), ("tipo_quirofano", models.CharField(default="media_complejidad", max_length=40)), ("disponibilidad", models.JSONField(default=list))], options={"ordering": ["nombre"]}),
        migrations.CreateModel(name="Patient", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("dni", models.CharField(max_length=20, unique=True)), ("nombre", models.CharField(max_length=255)), ("edad", models.IntegerField(blank=True, null=True)), ("obra_social", models.CharField(blank=True, max_length=120, null=True))], options={"ordering": ["nombre"]}),
        migrations.CreateModel(name="Specialty", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=120, unique=True)), ("estado", models.BooleanField(default=True)), ("compatible_tipos_quirofano", models.JSONField(default=list)), ("min_bloques", models.IntegerField(default=1)), ("max_bloques", models.IntegerField(default=10))], options={"ordering": ["nombre"]}),
        migrations.CreateModel(name="Supply", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("nombre", models.CharField(max_length=180, unique=True)), ("stock", models.IntegerField(default=0))]),
        migrations.AddField(model_name="intervention", name="especialidad", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intervenciones", to="surgeries.specialty")),
        migrations.CreateModel(name="MedicalStaffSpecialty", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("especialidad", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="surgeries.specialty")), ("personal_medico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="surgeries.medicalstaff"))]),
        migrations.AddField(model_name="medicalstaff", name="especialidades", field=models.ManyToManyField(related_name="personal_medico", through="surgeries.MedicalStaffSpecialty", to="surgeries.specialty")),
        migrations.CreateModel(name="MedicalStaffAvailability", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("dia", models.IntegerField()), ("inicio_minutos", models.IntegerField()), ("fin_minutos", models.IntegerField()), ("personal_medico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="disponibilidades", to="surgeries.medicalstaff"))], options={"ordering": ["dia"]}),
        migrations.CreateModel(name="Surgery", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("inicio", models.DateTimeField(blank=True, db_index=True, null=True)), ("fin", models.DateTimeField(blank=True, null=True)), ("byer", models.BooleanField(default=False)), ("sedacion", models.BooleanField(default=False)), ("estado", models.CharField(db_index=True, default="Pendiente", max_length=40)), ("observaciones", models.TextField(blank=True, null=True)), ("duracion_estimada_minutos", models.IntegerField(default=60)), ("prioridad_clinica", models.FloatField(default=1.0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("cirujano_forzado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cirugias_forzadas", to="surgeries.medicalstaff")), ("especialidad", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cirugias", to="surgeries.specialty")), ("paciente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cirugias", to="surgeries.patient")), ("sala", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cirugias", to="surgeries.operatingroom")), ("tipo_anestesia", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cirugias", to="surgeries.anesthesiatype"))], options={"ordering": [models.OrderBy(models.F("inicio"), nulls_last=True), "-created_at"]}),
        migrations.CreateModel(name="SurgerySupply", fields=[("id", models.CharField(default=surgeries.models.new_uuid, max_length=36, primary_key=True, serialize=False)), ("cantidad", models.IntegerField()), ("observaciones", models.TextField(blank=True, null=True)), ("cirugia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="insumos", to="surgeries.surgery")), ("insumo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lineas_cirugia", to="surgeries.supply"))]),
        migrations.CreateModel(name="SurgeryIntervention", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("orden", models.IntegerField(default=1)), ("cirugia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intervenciones", to="surgeries.surgery")), ("intervencion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cirugias", to="surgeries.intervention"))], options={"ordering": ["orden"]}),
        migrations.AddConstraint(model_name="intervention", constraint=models.UniqueConstraint(fields=("nombre", "especialidad"), name="uniq_intervention_specialty")),
        migrations.AddConstraint(model_name="medicalstaffspecialty", constraint=models.UniqueConstraint(fields=("personal_medico", "especialidad"), name="uniq_staff_specialty")),
        migrations.AddConstraint(model_name="medicalstaffavailability", constraint=models.UniqueConstraint(fields=("personal_medico", "dia"), name="uniq_staff_day")),
        migrations.AddConstraint(model_name="surgeryintervention", constraint=models.UniqueConstraint(fields=("cirugia", "intervencion"), name="uniq_surgery_intervention")),
    ]
