# Generated by Django 5.2.15 on 2026-06-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['nombre']},
        ),
    ]
